In [63]:
import pandas as pd
import numpy as np

df = pd.read_excel(
    "../data/raw/healthcare_portfolio_dataset.xlsx",
    sheet_name="Hospital_Full_Data"
)

df.head()

,Admission_ID,Patient_ID,Doctor_ID,Department_ID,Admission_Date,Discharge_Date,Diagnosis,Treatment,Admission_Type,Insurance_Type,...,Outcome,Readmission_30_Days,Patient_Name,Age,Gender,City,Doctor_Name,Experience_Years,Department_ID_Doctor,Department_Name
0,A000001,P10001,D141,DEP01,2025-02-22,2025-03-06,Cancer,Medication,Scheduled,Government,...,Recovered,No,Kavya Verma,82,Female,Thane,Dr. Karan Agarwal,23,DEP03,Cardiology
1,A000002,P10002,D112,DEP05,2024-06-24,2024-06-29,Skin Infection,Physiotherapy,Scheduled,Private,...,Recovered,No,Aarav Malhotra,5,Male,Kolhapur,Dr. Vikram Reddy,24,DEP04,Pediatrics
2,A000003,P10003,D148,DEP01,2024-07-18,2024-07-26,Skin Infection,Observation,Scheduled,Private,...,Recovered,Yes,Rahul Reddy,62,Male,Aurangabad,Dr. Karan Gupta,27,DEP05,Cardiology
3,A000004,P10004,D147,DEP07,2024-05-14,2024-05-15,Migraine,Radiotherapy,Emergency,Private,...,Improved,No,Vivaan Joshi,75,Female,Thane,Dr. Rahul Nair,11,DEP07,Gynecology
4,A000005,P10005,D111,DEP04,2024-10-10,2024-10-18,Hypertension,Minor Procedure,Scheduled,Private,...,Improved,No,Diya Joshi,55,Male,Nashik,Dr. Priya Singh,7,DEP04,General Medicine

##Structure of Dataset

In [64]:
df.shape

(15000, 23)

In [65]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 15000 entries, 0 to 14999
Data columns (total 23 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   Admission_ID          15000 non-null  str
 1   Patient_ID            15000 non-null  str
 2   Doctor_ID             15000 non-null  str
 3   Department_ID         15000 non-null  str
 4   Admission_Date        15000 non-null  datetime64[us]
 5   Discharge_Date        15000 non-null  datetime64[us]
 6   Diagnosis             14880 non-null  str
 7   Treatment             15000 non-null  str
 8   Admission_Type        15000 non-null  str
 9   Insurance_Type        14850 non-null  str
 10  Total_Bill_INR        15000 non-null  int64
 11  Length_of_Stay_Days   15000 non-null  int64
 12  Patient_Rating        14775 non-null  float64
 13  Outcome               15000 non-null  str
 14  Readmission_30_Days   15000 non-null  str
 15  Patient_Name          15000 non-null  str
 16  Age                   15000 non-null  int64
 17  Gender                15000 non-null  str
 18  City                  15000 non-null  str
 19  Doctor_Name           15000 non-null  str
 20  Experience_Years      15000 non-null  int64
 21  Department_ID_Doctor  15000 non-null  str
 22  Department_Name       15000 non-null  str
dtypes: datetime64[us](2), float64(1), int64(4), str(16)
memory usage: 2.6 MB

In [66]:
df.columns.tolist()

['Admission_ID',
 'Patient_ID',
 'Doctor_ID',
 'Department_ID',
 'Admission_Date',
 'Discharge_Date',
 'Diagnosis',
 'Treatment',
 'Admission_Type',
 'Insurance_Type',
 'Total_Bill_INR',
 'Length_of_Stay_Days',
 'Patient_Rating',
 'Outcome',
 'Readmission_30_Days',
 'Patient_Name',
 'Age',
 'Gender',
 'City',
 'Doctor_Name',
 'Experience_Years',
 'Department_ID_Doctor',
 'Department_Name']

In [67]:
df.isnull().sum()

Admission_ID              0
Patient_ID                0
Doctor_ID                 0
Department_ID             0
Admission_Date            0
Discharge_Date            0
Diagnosis               120
Treatment                 0
Admission_Type            0
Insurance_Type          150
Total_Bill_INR            0
Length_of_Stay_Days       0
Patient_Rating          225
Outcome                   0
Readmission_30_Days       0
Patient_Name              0
Age                       0
Gender                    0
City                      0
Doctor_Name               0
Experience_Years          0
Department_ID_Doctor      0
Department_Name           0
dtype: int64

##Duplicate check

In [69]:
df.duplicated().sum()

np.int64(0)

In [70]:
df["Admission_ID"].duplicated().sum()

np.int64(0)

##Missing Values Check

In [71]:
df[df["Diagnosis"].isnull()][
    ["Patient_ID", "Department_Name", "Treatment", "Total_Bill_INR"]
].head(10)

    Patient_ID   Department_Name      Treatment  Total_Bill_INR
47      P10048  General Medicine        Surgery          115500
49      P10050  General Medicine        Surgery           34400
174     P10175  General Medicine  Physiotherapy           61000
228     P10229        Cardiology  Physiotherapy           63800
234     P10235        Gynecology  Physiotherapy           60200
376     P10377  General Medicine   Radiotherapy           79300
390     P10391        Pediatrics   Chemotherapy           30700
397     P10398  General Medicine    Observation           54600
412     P10413        Pediatrics    Observation           29500
419     P10420       Dermatology   Radiotherapy           66400

In [72]:
df[df["Insurance_Type"].isnull()][
    ["Patient_ID", "Department_Name", "Diagnosis", "Total_Bill_INR"]
].head(10)

    Patient_ID   Department_Name       Diagnosis  Total_Bill_INR
72      P10073        Gynecology  Skin Infection          100500
139     P10140       Dermatology   Heart Disease           26500
174     P10175  General Medicine             NaN           61000
199     P10200  General Medicine        Diabetes           40600
261     P10262          Oncology       Arthritis          261200
316     P10317       Dermatology   Heart Disease           40600
414     P10415        Gynecology          Cancer          116500
428     P10429  General Medicine          Cancer           30200
521     P10522          Oncology    Hypertension          102900
647     P10648  General Medicine        Migraine           20800

##Date Validation

In [73]:
(df["Discharge_Date"] < df["Admission_Date"]).sum()

np.int64(0)

##Length_of_Stay_Days

In [74]:
calculated_los = (
    df["Discharge_Date"] - df["Admission_Date"]
).dt.days

(df["Length_of_Stay_Days"] != calculated_los).sum()

np.int64(0)

##Categorical values samjho

In [75]:
df["Department_Name"].value_counts()

Department_Name
General Medicine    3328
Orthopedics         2093
Cardiology          1981
Gynecology          1789
Dermatology         1681
Neurology           1475
Pediatrics          1472
Oncology            1181
Name: count, dtype: int64

In [76]:
df["Admission_Type"].value_counts()

Admission_Type
Scheduled    8349
Emergency    4466
Referral     2185
Name: count, dtype: int64

In [77]:
df["Insurance_Type"].value_counts()

Insurance_Type
Private       6290
Government    4183
Self-Pay      2584
Corporate     1793
Name: count, dtype: int64

In [78]:
df["Outcome"].value_counts()

Outcome
Recovered    7238
Improved     4033
Stable       2522
Referred      917
Deceased      290
Name: count, dtype: int64

##Data Cleaning

In [79]:
df["Diagnosis"] = df["Diagnosis"].fillna("Unknown")

In [80]:
df["Diagnosis"].isnull().sum()

np.int64(0)

In [81]:
df["Insurance_Type"] = df["Insurance_Type"].fillna("Unknown")

In [82]:
df["Insurance_Type"].isnull().sum()

np.int64(0)

##Saving File

In [83]:
df.to_csv(
    "../data/cleaned/healthcare_cleaned.csv",
    index=False
)

##EDA

In [84]:
df["Department_Name"].value_counts()

Department_Name
General Medicine    3328
Orthopedics         2093
Cardiology          1981
Gynecology          1789
Dermatology         1681
Neurology           1475
Pediatrics          1472
Oncology            1181
Name: count, dtype: int64

In [85]:
df.groupby("Department_Name")["Total_Bill_INR"].mean().sort_values(ascending=False)

Department_Name
Oncology            111602.878916
Cardiology           85762.039374
Neurology            76685.491525
Orthopedics          69997.133301
Gynecology           56030.240358
General Medicine     52416.256010
Pediatrics           43336.073370
Dermatology          39088.459250
Name: Total_Bill_INR, dtype: float64

In [86]:
department_summary = df.groupby("Department_Name").agg(
    Admissions=("Admission_ID", "count"),
    Average_Bill=("Total_Bill_INR", "mean")
).sort_values("Admissions", ascending=False)

department_summary

                  Admissions   Average_Bill
Department_Name
General Medicine        3328   52416.256010
Orthopedics             2093   69997.133301
Cardiology              1981   85762.039374
Gynecology              1789   56030.240358
Dermatology             1681   39088.459250
Neurology               1475   76685.491525
Pediatrics              1472   43336.073370
Oncology                1181  111602.878916

In [87]:
df.groupby("Department_Name")["Length_of_Stay_Days"].mean().sort_values(ascending=False)

Department_Name
Oncology            5.008467
Neurology           4.932881
Orthopedics         4.917821
Dermatology         4.896490
Gynecology          4.876467
General Medicine    4.867488
Cardiology          4.793034
Pediatrics          4.728261
Name: Length_of_Stay_Days, dtype: float64

In [88]:
df.groupby("Department_Name")["Total_Bill_INR"].sum().sort_values(ascending=False)

Department_Name
General Medicine    174441300
Cardiology          169894600
Orthopedics         146504000
Oncology            131803000
Neurology           113111100
Gynecology          100238100
Dermatology          65707700
Pediatrics           63790700
Name: Total_Bill_INR, dtype: int64

In [89]:
df.groupby("Department_Name")["Patient_Rating"].mean().sort_values(ascending=False)

Department_Name
Gynecology          3.996653
Cardiology          3.993634
Dermatology         3.981703
Oncology            3.976996
General Medicine    3.976970
Orthopedics         3.969424
Neurology           3.969353
Pediatrics          3.968069
Name: Patient_Rating, dtype: float64

In [90]:
df["Readmission_30_Days"].value_counts()

Readmission_30_Days
No     13221
Yes     1779
Name: count, dtype: int64

In [91]:
readmission_rate = (
    (df["Readmission_30_Days"] == "Yes").sum()
    / len(df)
) * 100

readmission_rate

np.float64(11.86)

In [92]:
df.groupby(["Department_Name", "Readmission_30_Days"]).size()

Department_Name   Readmission_30_Days
Cardiology        No                     1746
                  Yes                     235
Dermatology       No                     1494
                  Yes                     187
General Medicine  No                     2953
                  Yes                     375
Gynecology        No                     1599
                  Yes                     190
Neurology         No                     1281
                  Yes                     194
Oncology          No                     1045
                  Yes                     136
Orthopedics       No                     1831
                  Yes                     262
Pediatrics        No                     1272
                  Yes                     200
dtype: int64

In [93]:
readmission_by_dept = (
    df.groupby("Department_Name")["Readmission_30_Days"]
      .apply(lambda x: (x == "Yes").mean() * 100)
      .sort_values(ascending=False)
)

readmission_by_dept

Department_Name
Pediatrics          13.586957
Neurology           13.152542
Orthopedics         12.517917
Cardiology          11.862696
Oncology            11.515665
General Medicine    11.268029
Dermatology         11.124331
Gynecology          10.620458
Name: Readmission_30_Days, dtype: float64

In [94]:
df["Gender"].value_counts()

Gender
Male      7497
Female    7226
Other      277
Name: count, dtype: int64

In [95]:
df["Admission_Type"].value_counts()

Admission_Type
Scheduled    8349
Emergency    4466
Referral     2185
Name: count, dtype: int64

In [96]:
df["Insurance_Type"].value_counts()

Insurance_Type
Private       6290
Government    4183
Self-Pay      2584
Corporate     1793
Unknown        150
Name: count, dtype: int64

In [97]:
df.groupby("Insurance_Type")["Total_Bill_INR"].sum().sort_values(ascending=False)

Insurance_Type
Private       403381200
Government    270179000
Self-Pay      164910700
Corporate     117559900
Unknown         9459700
Name: Total_Bill_INR, dtype: int64

In [98]:
df["Treatment"].value_counts()

Treatment
Medication         4568
Observation        2929
Surgery            2403
Physiotherapy      2098
Minor Procedure    1262
Chemotherapy       1033
Radiotherapy        707
Name: count, dtype: int64

In [99]:
df.groupby("Treatment")["Total_Bill_INR"].mean().sort_values(ascending=False)

Treatment
Surgery            116252.767374
Chemotherapy       108989.545015
Radiotherapy        99102.970297
Minor Procedure     61984.152139
Physiotherapy       49587.845567
Medication          44622.920315
Observation         40077.261864
Name: Total_Bill_INR, dtype: float64

In [100]:
##Monthly Admission Trend
df["Admission_Month"] = df["Admission_Date"].dt.to_period("M")
df["Admission_Month"]

0        2025-02
1        2024-06
2        2024-07
3        2024-05
4        2024-10
          ...
14995    2025-06
14996    2024-04
14997    2025-06
14998    2025-12
14999    2025-01
Name: Admission_Month, Length: 15000, dtype: period[M]

In [101]:
monthly_admissions = (
    df.groupby("Admission_Month")
      .size()
)

monthly_admissions

Admission_Month
2024-01    616
2024-02    624
2024-03    666
2024-04    601
2024-05    683
2024-06    629
2024-07    627
2024-08    611
2024-09    588
2024-10    652
2024-11    617
2024-12    567
2025-01    633
2025-02    585
2025-03    641
2025-04    649
2025-05    674
2025-06    579
2025-07    590
2025-08    663
2025-09    638
2025-10    620
2025-11    619
2025-12    628
Freq: M, dtype: int64

In [ ]:
##Which diagnoses are most common in the hospital?
df["Diagnosis"].value_counts()

Diagnosis
Heart Disease      1543
Skin Infection     1541
Migraine           1510
Pneumonia          1507
Hypertension       1502
Diabetes           1493
Fracture           1459
Cancer             1456
Arthritis          1449
Viral Infection    1420
Unknown             120
Name: count, dtype: int64

In [121]:
df.groupby("Diagnosis")["Total_Bill_INR"].mean().sort_values(ascending=False)

Diagnosis
Unknown            73222.500000
Diabetes           66184.661755
Skin Infection     65794.419208
Cancer             64792.513736
Hypertension       64561.784288
Heart Disease      64394.102398
Pneumonia          64349.966821
Fracture           64130.980123
Arthritis          63476.949620
Migraine           62626.622517
Viral Infection    62495.985915
Name: Total_Bill_INR, dtype: float64

In [103]:
#. Diagnosis-wise Patient Volume
diagnosis_volume = (
    df["Diagnosis"]
    .value_counts()
)

diagnosis_volume

Diagnosis
Heart Disease      1543
Skin Infection     1541
Migraine           1510
Pneumonia          1507
Hypertension       1502
Diabetes           1493
Fracture           1459
Cancer             1456
Arthritis          1449
Viral Infection    1420
Unknown             120
Name: count, dtype: int64

In [104]:
#Length of Stay vs Billing 
los_billing = (
    df.groupby("Length_of_Stay_Days")["Total_Bill_INR"]
      .mean()
)

los_billing

Length_of_Stay_Days
1      56761.778563
2      59425.806452
3      61476.099018
4      63841.633466
5      64234.071054
6      66801.216893
7      64908.571429
8      67217.615894
9      74073.244782
10     71963.915094
11     74483.904110
12     81352.000000
13     83041.333333
14     88987.155963
15     83452.380952
16     89098.245614
17     92774.358974
18     78642.857143
19     71341.666667
20     92070.000000
21     97544.444444
22    104125.000000
23    107875.000000
24     74325.000000
25     77200.000000
28    207000.000000
29    107200.000000
Name: Total_Bill_INR, dtype: float64

In [105]:
#Readmitted vs Non-Readmitted Comparison 
readmission_comparison = (
    df.groupby("Readmission_30_Days")
      .agg(
          Average_Age=("Age", "mean"),
          Average_LOS=("Length_of_Stay_Days", "mean"),
          Average_Bill=("Total_Bill_INR", "mean")
      )
)

readmission_comparison

                     Average_Age  Average_LOS  Average_Bill
Readmission_30_Days
No                     45.289691     4.884048  64361.379623
Yes                    45.197302     4.789770  64400.618325

In [106]:
# Correlation Analysis 
correlation = df[
    [
        "Age",
        "Total_Bill_INR",
        "Length_of_Stay_Days",
        "Patient_Rating",
        "Experience_Years"
    ]
].corr()

correlation

,Age,Total_Bill_INR,Length_of_Stay_Days,Patient_Rating,Experience_Years
Age,1.000000,-0.006369,0.003965,0.014098,0.007001
Total_Bill_INR,-0.006369,1.000000,0.135524,0.006245,0.005784
Length_of_Stay_Days,0.003965,0.135524,1.000000,0.008461,-0.010323
Patient_Rating,0.014098,0.006245,0.008461,1.000000,-0.001866
Experience_Years,0.007001,0.005784,-0.010323,-0.001866,1.000000

##Statistics

In [107]:
df.describe().T

,count,mean,min,25%,50%,75%,max,std
Admission_Date,15000,2024-12-30 02:37:32.160000,2024-01-01 00:00:00,2024-06-26 00:00:00,2025-01-01 00:00:00,2025-07-01 00:00:00,2025-12-31 00:00:00,NaN
Discharge_Date,15000,2025-01-03 23:34:27.840000,2024-01-03 00:00:00,2024-07-01 00:00:00,2025-01-07 00:00:00,2025-07-06 00:00:00,2026-01-13 00:00:00,NaN
Total_Bill_INR,15000.0,64366.033333,3000.0,35000.0,51200.0,79500.0,421000.0,44803.231382
Length_of_Stay_Days,15000.0,4.872867,1.0,2.0,4.0,6.0,29.0,3.288985
Patient_Rating,14775.0,3.979371,1.5,3.6,4.0,4.4,5.0,0.620762
Age,15000.0,45.278733,1.0,23.0,45.5,68.0,90.0,25.9179
Experience_Years,15000.0,15.654,2.0,8.0,15.0,23.0,30.0,8.435415

In [108]:
df["Total_Bill_INR"].describe()

count     15000.000000
mean      64366.033333
std       44803.231382
min        3000.000000
25%       35000.000000
50%       51200.000000
75%       79500.000000
max      421000.000000
Name: Total_Bill_INR, dtype: float64

In [109]:
df["Total_Bill_INR"].describe()

count     15000.000000
mean      64366.033333
std       44803.231382
min        3000.000000
25%       35000.000000
50%       51200.000000
75%       79500.000000
max      421000.000000
Name: Total_Bill_INR, dtype: float64

In [110]:
Q1 = df["Total_Bill_INR"].quantile(0.25)
Q3 = df["Total_Bill_INR"].quantile(0.75)

IQR = Q3 - Q1

lower_limit = Q1 - 1.5 * IQR
upper_limit = Q3 + 1.5 * IQR

print("Lower Limit:", lower_limit)
print("Upper Limit:", upper_limit)

Lower Limit: -31750.0
Upper Limit: 146250.0

In [111]:
outliers = df[
    (df["Total_Bill_INR"] < lower_limit) |
    (df["Total_Bill_INR"] > upper_limit)
]

print("Number of outliers:", len(outliers))

Number of outliers: 895

In [112]:
outliers[[
    "Patient_ID",
    "Department_Name",
    "Diagnosis",
    "Treatment",
    "Length_of_Stay_Days",
    "Total_Bill_INR"
]].sort_values(
    "Total_Bill_INR",
    ascending=False
).head(10)

,Patient_ID,Department_Name,Diagnosis,Treatment,Length_of_Stay_Days,Total_Bill_INR
14533,P24534,Oncology,Heart Disease,Surgery,1,421000
1148,P11149,Oncology,Skin Infection,Surgery,3,412800
13185,P23186,Oncology,Diabetes,Surgery,7,373800
13246,P23247,Oncology,Viral Infection,Surgery,9,368400
2223,P12224,Cardiology,Viral Infection,Surgery,2,364600
10967,P20968,Oncology,Cancer,Chemotherapy,3,358900
3717,P13718,Oncology,Fracture,Chemotherapy,7,357700
8914,P18915,Oncology,Skin Infection,Chemotherapy,6,345800
6990,P16991,Oncology,Diabetes,Surgery,8,339800
7583,P17584,Oncology,Unknown,Surgery,10,334600

In [113]:
outliers["Treatment"].value_counts()

Treatment
Surgery            568
Chemotherapy       211
Radiotherapy       103
Minor Procedure     12
Medication           1
Name: count, dtype: int64

In [114]:
outliers["Department_Name"].value_counts()

Department_Name
Cardiology          269
Oncology            263
Orthopedics         154
Neurology           148
Gynecology           31
General Medicine     28
Pediatrics            2
Name: count, dtype: int64

In [115]:
df["Patient_Rating"].describe()

count    14775.000000
mean         3.979371
std          0.620762
min          1.500000
25%          3.600000
50%          4.000000
75%          4.400000
max          5.000000
Name: Patient_Rating, dtype: float64

In [116]:
df["Age"].describe()

count    15000.000000
mean        45.278733
std         25.917900
min          1.000000
25%         23.000000
50%         45.500000
75%         68.000000
max         90.000000
Name: Age, dtype: float64

In [117]:
#T-test — Readmission vs Average Bill
from scipy.stats import ttest_ind

readmitted_bill = df.loc[
    df["Readmission_30_Days"] == "Yes",
    "Total_Bill_INR"
]

not_readmitted_bill = df.loc[
    df["Readmission_30_Days"] == "No",
    "Total_Bill_INR"
]

t_stat, p_value = ttest_ind(
    readmitted_bill,
    not_readmitted_bill,
    equal_var=False
)

print("T-statistic:", t_stat)
print("P-value:", p_value)

T-statistic: 0.034999720080142155
P-value: 0.9720830063372626

In [118]:
##ANOVA -Kya different departments ke average bills mein actual difference hai, ya sirf random variation hai?
from scipy.stats import f_oneway

groups = [
    group["Total_Bill_INR"].values
    for _, group in df.groupby("Department_Name")
]

f_stat, p_value = f_oneway(*groups)

print("F-statistic:", f_stat)
print("P-value:", p_value)

F-statistic: 550.5559648317771
P-value: 0.0

In [119]:
##Chi-square test-Kya Admission Type (Emergency/Scheduled/Referral) aur 30-day Readmission ke beech relationship hai?
from scipy.stats import chi2_contingency

table = pd.crosstab(
    df["Admission_Type"],
    df["Readmission_30_Days"]
)

chi2, p_value, dof, expected = chi2_contingency(table)

print("Chi-square statistic:", chi2)
print("P-value:", p_value)

Chi-square statistic: 13.909160937805353
P-value: 0.0009542541962627762

In [120]:
##Confidence Interval-Overall average hospital bill ka reasonable range kya hai?
from scipy.stats import t

mean_bill = df["Total_Bill_INR"].mean()
std_bill = df["Total_Bill_INR"].std()
n = df["Total_Bill_INR"].count()

confidence = 0.95
alpha = 1 - confidence

margin_error = (
    t.ppf(1 - alpha/2, n - 1)
    * (std_bill / np.sqrt(n))
)

lower = mean_bill - margin_error
upper = mean_bill + margin_error

print("Mean Bill:", mean_bill)
print("95% Confidence Interval:", lower, "to", upper)

Mean Bill: 64366.03333333333
95% Confidence Interval: 63648.98761483839 to 65083.079051828274